### ISSUE TITLE
MENUS JUST GOING AWAY?? SPAWNING IN JUST MAKES YOU INVISIBLE AND MAKE YOU JUMP SLOWLY????

### ISSUE THREAD

**Issue by takowacki** [Daisreich/Civilian2#10]
I tried installing some addons that might change the gameplay, and for some reason all the UI elements just disappear, and the only thing I see is the character select screen background. I tried uninstalling everything but Civilian 2 but the menus were still empty and I couldn't do anything. The only way I found a fix for this was by deleting all the garry's mod files in steamapps and reinstalling gmod again. I don't know what mods caused it.

**Comment by takowacki** [comment]
![20230611042725_1](https://github.com/Daisreich/Civilian2/assets/125357520/c0b06def-9187-4301-b7d7-14f8b1adeba2)
this is literally all that i can see

**Comment by takowacki** [comment]
i dont understand what im doing wrong, I uninstalled all of my addons and reinstalled garrys mod four times to try and get this shit to work. i literally have no mods installed other than civilian 2 and it still isn't fucking working. i don't know what's going on, this is such a buggy mess.

**Comment by takowacki** [comment]
and everytime i was able to access the menu it would just spawn me in invisible with no abilities, with a slow ass walk and a slow ass jump

**Comment by Daisreich** [comment]
you ok

**Comment by takowacki** [comment]
> you ok

no. cause no matter what i do or what i install the mod just does not work at ALL

**Comment by takowacki** [comment]
> you ok

like can i get some help here, why the fuck does this mod break when I don't have anything else fucking downloaded
![20230611155829_1](https://github.com/Daisreich/Civilian2/assets/125357520/ef7a939a-0aaa-4909-8d96-ae70a2fe09da)

**Comment by Daisreich** [comment]
can you try disabling tf_tfc_model_override? that has been causing a lot of issues lately

**Comment by takowacki** [comment]
> can you try disabling tf_tfc_model_override? that has been causing a lot of issues lately


there's no command called  tf_tfc_model_override
